# Generated by Django 2.0.2 on 2018-03-15 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('recovery_answer', models.CharField(max_length=50)),
                ('recovery_email', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 3, 15, 18, 19, 58, 890714, tzinfo=utc))),
                ('last_updated_on', models.DateTimeField()),
                ('deleted_on', models.DateTimeField()),
            ],
        ),
    ]
