# Generated by Django 2.0.4 on 2018-05-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emptimeclklogmgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('recovery_answer', models.CharField(max_length=100)),
                ('recovery_email', models.CharField(max_length=100)),
            ],
        ),
    ]
