# Generated by Django 2.0.2 on 2018-03-22 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emptimeclklogmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='deleted_on',
            field=models.DateTimeField(blank='True', default=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_updated_on',
            field=models.DateTimeField(blank='True', default=''),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='deleted_on',
            field=models.DateTimeField(blank='True', default=''),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='middle_name',
            field=models.CharField(blank='True', default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='phone_number',
            field=models.IntegerField(blank='True', null='True'),
        ),
    ]
