# Generated by Django 2.0.2 on 2018-03-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emptimeclklogmgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='deleted_on',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_updated_on',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='recovery_answer',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='recovery_email',
        ),
    ]
