# Generated by Django 2.0.4 on 2018-05-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emptimeclklogmgmt', '0002_employeeaes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaes',
            name='password',
            field=models.BinaryField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeaes',
            name='recovery_answer',
            field=models.BinaryField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeaes',
            name='recovery_email',
            field=models.BinaryField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeaes',
            name='username',
            field=models.BinaryField(max_length=100),
        ),
    ]
