# Generated by Django 2.0.2 on 2018-03-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emptimeclklogmgmt', '0002_auto_20180322_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='deleted_on',
            field=models.DateTimeField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_updated_on',
            field=models.DateTimeField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='deleted_on',
            field=models.DateTimeField(blank='True', null='True'),
        ),
    ]
