# Generated by Django 2.0.2 on 2018-03-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emptimeclklogmgmt', '0003_auto_20180322_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
