# Generated by Django 2.0.4 on 2018-05-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emptimeclklogmgmt', '0003_auto_20180504_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfoAES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('middle_name', models.CharField(blank=True, default='', max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('department', models.CharField(default='', max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=500, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emptimeclklogmgmt.Employee')),
            ],
        ),
        migrations.AlterField(
            model_name='employeeaes',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='employeeaes',
            name='recovery_answer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='employeeaes',
            name='recovery_email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='employeeaes',
            name='username',
            field=models.CharField(max_length=500),
        ),
    ]
