# Generated by Django 2.0.4 on 2018-05-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emptimeclklogmgmt', '0004_auto_20180504_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfoaes',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emptimeclklogmgmt.EmployeeAES'),
        ),
    ]
