# Generated by Django 2.0.2 on 2018-03-22 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emptimeclklogmgmt', '0004_auto_20180322_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('recovery_answer', models.CharField(max_length=20)),
                ('recovery_email', models.CharField(max_length=20)),
                ('last_updated_on', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(blank=True, default='', max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
